[package]
name = "day_13"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
serde = { version = "1.0.211", features = ["derive"] }
serde_json = "1.0.132"
xmas = { version = "0.1.0", path = "../xmas" }
